#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate 1000-word Spanish frequency list"""

# Comprehensive Spanish 1000-word frequency list (based on corpora analysis)
spanish_words = [
    (1, "de", "of/from"), (2, "que", "that/which"), (3, "no", "no/not"), (4, "a", "to/at"),
    (5, "la", "the (fem)"), (6, "el", "the (masc)"), (7, "y", "and"), (8, "en", "in/on/at"),
    (9, "un", "a/an"), (10, "ser", "to be (perm)"), (11, "se", "oneself/-self"), 
    (12, "por", "for/by/through"), (13, "qué", "what/which"), (14, "me", "me/to me"),
    (15, "una", "a/an (fem)"), (16, "te", "you (obj)"), (17, "los", "the (masc pl)"),
    (18, "con", "with"), (19, "para", "for/to"), (20, "mi", "my"), (21, "estar", "to be (temp/loc)"),
    (22, "si", "if/whether"), (23, "bien", "well/good"), (24, "pero", "but"), (25, "yo", "I"),
    (26, "eso", "that (neut)"), (27, "las", "the (fem pl)"), (28, "sí", "yes"), (29, "su", "his/her/your"),
    (30, "tu", "your (inf)"), (31, "aquí", "here"), (32, "del", "of the/from the"), (33, "al", "to the"),
    (34, "como", "as/like/how"), (35, "le", "him/her/you (ind obj)"), (36, "más", "more"),
    (37, "esto", "this (neut)"), (38, "ya", "already"), (39, "todo", "all/everything"),
    (40, "esta", "this (fem)"), (41, "muy", "very/much"), (42, "hay", "there is/are"),
    (43, "ahora", "now"), (44, "algo", "something"), (45, "este", "this (masc)"),
    (46, "nosotros", "we/us"), (47, "nada", "nothing"), (48, "cuando", "when"),
    (49, "ha", "has (aux)"), (50, "sé", "I know"),
    (51, "así", "like that/so"), (52, "puedo", "I can"), (53, "cómo", "how"), (54, "quiero", "I want"),
    (55, "sólo", "only"), (56, "soy", "I am"), (57, "tiene", "has"), (58, "gracias", "thanks"),
    (59, "o", "or"), (60, "él", "he/him"), (61, "bueno", "good"), (62, "fue", "was/went"),
    (63, "hacer", "to do/make"), (64, "son", "they/you (formal) are"), (65, "todos", "everyone/all"),
    (66, "era", "was (imperfect)"), (67, "eres", "you are (inf)"), (68, "vez", "time/instance"),
    (69, "tienes", "you have (inf)"), (70, "creo", "I think/believe"), (71, "ella", "she/her"),
    (72, "he", "I have (aux-archaic)"), (73, "ese", "that (masc)"), (74, "voy", "I go/am going"),
    (75, "puede", "can/may"), (76, "sabes", "you know (inf)"), (77, "hola", "hello"),
    (78, "sus", "his/her/their"), (79, "porque", "because"), (80, "dios", "god"),
    (81, "quién", "who/whom"), (82, "nunca", "never"), (83, "dónde", "where"),
    (84, "quieres", "you want (inf)"), (85, "casa", "house/home"), (86, "favor", "favor"),
    (87, "esa", "that (fem)"), (88, "dos", "two"), (89, "tan", "so/as"),
    (90, "señor", "sir/Mr./man"), (91, "tiempo", "time/weather"), (92, "verdad", "truth"),
    (93, "estaba", "was (imperfect)"), (94, "mejor", "better/best"), (95, "están", "they/you are"),
    (96, "va", "goes"), (97, "hombre", "man"), (98, "usted", "you (formal)"),
    (99, "mucho", "much/many"), (100, "hace", "does/makes"),
    (101, "querer", "to want/love"), (102, "nuevo", "new"), (103, "noche", "night/evening"),
    (104, "esta", "this (fem)"), (105, "estos", "these (masc)"), (106, "vida", "life"),
    (107, "otro", "other/another"), (108, "poco", "little/bit"), (109, "mi", "my"),
    (110, "padre", "father"), (111, "trabajo", "work/job"), (112, "mismo", "same"),
    (113, "ese", "that (masc)"), (114, "mira", "look"), (115, "tal", "such"),
    (116, "mejor", "better/best"), (117, "ahora", "now"), (118, "pasado", "past"),
    (119, "ante", "before/in face of"), (120, "aunque", "although"), (121, "después", "after"),
    (122, "casa", "house"), (123, "hecho", "fact/deed"), (124, "dice", "says"),
    (125, "años", "years"), (126, "gran", "large/great"), (127, "nuestro", "our"),
    (128, "día", "day"), (129, "mundo", "world"), (130, "tres", "three"),
    (131, "hacia", "toward"), (132, "antes", "before"), (133, "tengo", "I have"),
    (134, "tiempo", "time"), (135, "durante", "during"), (136, "quién", "who"),
    (137, "mientras", "while"), (138, "dentro", "inside/within"), (139, "encima", "on top"),
    (140, "debajo", "below/under"), (141, "cerca", "near"), (142, "lejos", "far"),
    (143, "junto", "together/next to"), (144, "según", "according to"), (145, "mediante", "by means of"),
    (146, "pesar", "despite"), (147, "volver", "to return"), (148, "pedir", "to ask for"),
    (149, "seguir", "to follow/continue"), (150, "encontrar", "to find"),
    (151, "dejar", "to leave/allow"), (152, "traer", "to bring"), (153, "llevar", "to carry/wear"),
    (154, "tomar", "to take"), (155, "dar", "to give"), (156, "poner", "to put"),
    (157, "hablar", "to speak"), (158, "entrar", "to enter"), (159, "salir", "to leave/go out"),
    (160, "sentir", "to feel"), (161, "vivir", "to live"), (162, "trabajar", "to work"),
    (163, "estudiar", "to study"), (164, "conocer", "to know"), (165, "parecer", "to seem"),
    (166, "quedar", "to stay/remain"), (167, "llegar", "to arrive"), (168, "comenzar", "to begin"),
    (169, "terminar", "to finish"), (170, "esperar", "to wait/hope"), (171, "olvidar", "to forget"),
    (172, "deber", "to owe/must"), (173, "poder", "can/may"), (174, "saber", "to know"),
    (175, "querer", "to want"), (176, "pensar", "to think"), (177, "recordar", "to remember"),
    (178, "mirar", "to look"), (179, "escuchar", "to listen"), (180, "ver", "to see"),
    (181, "comer", "to eat"), (182, "beber", "to drink"), (183, "dormir", "to sleep"),
    (184, "descansar", "to rest"), (185, "correr", "to run"), (186, "andar", "to walk"),
    (187, "subir", "to go up"), (188, "bajar", "to go down"), (189, "abrir", "to open"),
    (190, "cerrar", "to close"), (191, "escribir", "to write"), (192, "leer", "to read"),
    (193, "contar", "to count/tell"), (194, "llamar", "to call"), (195, "responder", "to answer"),
    (196, "preguntar", "to ask"), (197, "creer", "to think/believe"), (198, "pasar", "to pass"),
    (199, "cambiar", "to change"), (200, "variar", "to vary"),
    (201, "aumentar", "to increase"), (202, "disminuir", "to decrease"), (203, "mejorar", "to improve"),
    (204, "empeorar", "to worsen"), (205, "comenzar", "to start"), (206, "terminar", "to end"),
    (207, "continuar", "to continue"), (208, "seguir", "to follow"), (209, "cesar", "to stop"),
    (210, "durar", "to last"), (211, "ocurrir", "to happen"), (212, "suceder", "to occur"),
    (213, "resultar", "to result"), (214, "producir", "to produce"), (215, "causar", "to cause"),
    (216, "provocar", "to provoke"), (217, "permitir", "to allow"), (218, "prohibir", "to forbid"),
    (219, "obligar", "to force"), (220, "ayudar", "to help"), (221, "servir", "to serve"),
    (222, "usar", "to use"), (223, "aplicar", "to apply"), (224, "emplear", "to use/employ"),
    (225, "realizar", "to carry out"), (226, "efectuar", "to effect"), (227, "ejecutar", "to execute"),
    (228, "llevar a cabo", "to carry out"), (229, "realizar", "to perform"), (230, "desempeñar", "to perform"),
    (231, "ejercer", "to exercise"), (232, "practicar", "to practice"), (233, "entrenar", "to train"),
    (234, "prepara", "to prepare"), (235, "planear", "to plan"), (236, "programar", "to program"),
    (237, "organizar", "to organize"), (238, "coordinar", "to coordinate"), (239, "dirigir", "to direct"),
    (240, "comandar", "to command"), (241, "gobernar", "to govern"), (242, "controlar", "to control"),
    (243, "manejar", "to manage"), (244, "administrar", "to administrate"), (245, "gestionar", "to manage"),
    (246, "supervisar", "to supervise"), (247, "inspeccionar", "to inspect"), (248, "examinar", "to examine"),
    (249, "investigar", "to investigate"), (250, "estudiar", "to study"),
    (251, "analizar", "to analyze"), (252, "comparar", "to compare"), (253, "contrastar", "to contrast"),
    (254, "distinguir", "to distinguish"), (255, "diferenciar", "to differentiate"),
    (256, "identificar", "to identify"), (257, "reconocer", "to recognize"), (258, "admitir", "to admit"),
    (259, "aceptar", "to accept"), (260, "rechazar", "to reject"), (261, "descartar", "to discard"),
    (262, "eliminar", "to eliminate"), (263, "suprimir", "to suppress"), (264, "cancelar", "to cancel"),
    (265, "anular", "to annul"), (266, "revocas", "to revoke"), (267, "derogar", "to repeal"),
    (268, "suspender", "to suspend"), (269, "interrumpir", "to interrupt"), (270, "pausar", "to pause"),
    (271, "reanudar", "to resume"), (272, "recoiptar", "to recover"), (273, "recuperarse", "to recover"),
    (274, "restablecerse", "to recover"), (275, "sanar", "to heal"), (276, "curar", "to cure"),
    (277, "mejorar", "to improve"), (278, "aliviar", "to relieve"), (279, "ayudar", "to help"),
    (280, "socorrer", "to aid"), (281, "asistir", "to assist"), (282, "apoyar", "to support"),
    (283, "respaldar", "to back"), (284, "sostener", "to hold"), (285, "mantener", "to maintain"),
    (286, "preservar", "to preserve"), (287, "proteger", "to protect"), (288, "defender", "to defend"),
    (289, "guardar", "to keep/guard"), (290, "custodiar", "to keep"), (291, "vigilar", "to watch"),
    (292, "observar", "to observe"), (293, "contemplar", "to contemplate"), (294, "considerar", "to consider"),
    (295, "reflexionar", "to reflect"), (296, "meditar", "to meditate"), (297, "deliberar", "to deliberate"),
    (298, "pensar", "to think"), (299, "razonar", "to reason"), (300, "argumentar", "to argue"),
    (301, "discutir", "to discuss"), (302, "debatir", "to debate"), (303, "contender", "to contend"),
    (304, "competir", "to compete"), (305, "rivalizar", "to rival"), (306, "jugar", "to play"),
    (307, "divertirse", "to enjoy"), (308, "distraerse", "to distract oneself"), (309, "entretenerse", "to amuse oneself"),
    (310, "relajarse", "to relax"), (311, "descansar", "to rest"), (312, "reposar", "to rest"),
    (313, "dormir", "to sleep"), (314, "despertar", "to wake"), (315, "levantarse", "to get up"),
    (316, "acostarse", "to go to bed"), (317, "sentarse", "to sit down"), (318, "pararse", "to stand up"),
    (319, "inclinarse", "to lean"), (320, "agacharse", "to bend down"), (321, "estirarse", "to stretch"),
    (322, "moverse", "to move"), (323, "moverse", "to stir"), (324, "girar", "to turn"),
    (325, "rodar", "to roll"), (326, "deslizarse", "to slide"), (327, "resbalar", "to slip"),
    (328, "tropezar", "to stumble"), (329, "caerse", "to fall"), (330, "levantarse", "to get up"),
    (331, "saltar", "to jump"), (332, "brincar", "to hop"), (333, "lanzar", "to throw"),
    (334, "arrojar", "to throw"), (335, "tirar", "to throw"), (336, "alcanzar", "to reach"),
    (337, "coger", "to grasp"), (338, "asir", "to seize"), (339, "agarrar", "to grab"),
    (340, "empuñar", "to wield"), (341, "sostener", "to hold"), (342, "aguantar", "to bear"),
    (343, "resistir", "to resist"), (344, "tolerar", "to tolerate"), (345, "soportar", "to bear"),
    (346, "aguantar", "to bear"), (347, "sufrir", "to suffer"), (348, "padecer", "to suffer"),
    (349, "adolece", "to suffer"), (350, "lamentar", "to regret"), (351, "deplorar", "to deplore"),
    (352, "censurar", "to censure"), (353, "condenar", "to condemn"), (354, "reprobar", "to disapprove"),
    (355, "reprender", "to reprimand"), (356, "regañar", "to scold"), (357, "gritar", "to shout"),
    (358, "vociferar", "to vociferate"), (359, "bramar", "to bellow"), (360, "rugir", "to roar"),
    (361, "gruñir", "to growl"), (362, "ladrar", "to bark"), (363, "maullar", "to meow"),
    (364, "chillar", "to squeal"), (365, "gritar", "to scream"), (366, "aullar", "to howl"),
    (367, "cantar", "to sing"), (368, "tararear", "to hum"), (369, "silbar", "to whistle"),
    (370, "susurrar", "to whisper"), (371, "murmurar", "to murmur"), (372, "refunfuñar", "to grumble"),
    (373, "resoplar", "to snort"), (374, "resollar", "to breathe heavily"), (375, "jadear", "to pant"),
    (376, "boquear", "to gasp"), (377, "toser", "to cough"), (378, "estornudar", "to sneeze"),
    (379, "sorbetear", "to sip"), (380, "chupar", "to suck"), (381, "lamer", "to lick"),
    (382, "morder", "to bite"), (383, "masticar", "to chew"), (384, "tragar", "to swallow"),
    (385, "vomitar", "to vomit"), (386, "escupir", "to spit"), (387, "orinar", "to urinate"),
    (388, "defecar", "to defecate"), (389, "transpirar", "to perspire"), (390, "sudar", "to sweat"),
    (391, "sollozar", "to sob"), (392, "llorar", "to cry"), (393, "gemir", "to moan"),
    (394, "quejarse", "to complain"), (395, "lagrimear", "to tear"), (396, "suspirar", "to sigh"),
    (397, "exasperarse", "to exasperate"), (398, "irritarse", "to irritate"), (399, "enojarse", "to get angry"),
    (400, "furor", "fury"), (401, "rabia", "rage"), (402, "cólera", "anger"),
    (403, "ira", "wrath"), (404, "rencor", "resentment"), (405, "odio", "hate"),
    (406, "desprecio", "contempt"), (407, "desdén", "disdain"), (408, "menosprecio", "underestimation"),
    (409, "miedo", "fear"), (410, "temor", "dread"), (411, "pánico", "panic"),
    (412, "terror", "terror"), (413, "horror", "horror"), (414, "espanto", "fright"),
    (415, "susto", "scare"), (416, "alarma", "alarm"), (417, "aprensión", "apprehension"),
    (418, "inquietud", "uneasiness"), (419, "ansiedad", "anxiety"), (420, "angustia", "anguish"),
    (421, "tristeza", "sadness"), (422, "melancolía", "melancholy"), (423, "pesar", "sorrow"),
    (424, "duelo", "grief"), (425, "luto", "mourn"), (426, "dolor", "pain"),
    (427, "sufrimiento", "suffering"), (428, "agonia", "agony"), (429, "tormento", "torment"),
    (430, "martirio", "martyrdom"), (431, "suplicio", "torture"), (432, "castigo", "punishment"),
    (433, "pena", "penalty"), (434, "sanción", "sanction"), (435, "multa", "fine"),
    (436, "confiscación", "confiscation"), (437, "decomiso", "seizure"), (438, "embargo", "embargo"),
    (439, "secuestro", "seizure"), (440, "privación", "privation"), (441, "pérdida", "loss"),
    (442, "detrimento", "detriment"), (443, "perjuicio", "harm"), (444, "daño", "damage"),
    (445, "quebranto", "loss"), (446, "menoscabo", "diminishment"), (447, "merma", "diminishment"),
    (448, "reducción", "reduction"), (449, "descenso", "descent"), (450, "baja", "decline"),
    (451, "alza", "rise"), (452, "aumento", "increase"), (453, "incremento", "increase"),
    (454, "acrecentamiento", "increase"), (455, "mejora", "improvement"), (456, "progreso", "progress"),
    (457, "adelanto", "advance"), (458, "avance", "advance"), (459, "desarrollo", "development"),
    (460, "crecimiento", "growth"), (461, "ampliación", "expansion"), (462, "extensión", "extension"),
    (463, "prolongación", "prolongation"), (464, "alargamiento", "lengthening"), (465, "dilatación", "dilatation"),
    (466, "expansión", "expansion"), (467, "difusión", "diffusion"), (468, "propagación", "propagation"),
    (469, "diseminación", "dissemination"), (470, "dispersión", "dispersal"),
    (471, "distribución", "distribution"), (472, "reparto", "distribution"), (473, "división", "division"),
    (474, "partición", "partition"), (475, "segmentación", "segmentation"), (476, "desagregación", "disaggregation"),
    (477, "disgregación", "disaggregation"), (478, "separación", "separation"), (479, "alejamiento", "separation"),
    (480, "distanciamiento", "estrangement"), (481, "ruptura", "rupture"), (482, "quiebre", "break"),
    (483, "fractura", "fracture"), (484, "grieta", "crack"), (485, "hendidura", "slit"),
    (486, "abertura", "opening"), (487, "agujero", "hole"), (488, "cavidad", "cavity"),
    (489, "hueco", "hollow"), (490, "vacío", "empty"), (491, "blanco", "blank"),
    (492, "espacio", "space"), (493, "distancia", "distance"), (494, "intervalo", "interval"),
    (495, "período", "period"), (496, "lapso", "lapse"), (497, "rato", "while"),
    (498, "momento", "moment"), (499, "instante", "instant"), (500, "segundo", "second"),
    (501, "trice", "trice"), (502, "suspensión", "suspension"), (503, "pausa", "pause"),
    (504, "intermisión", "intermission"), (505, "descanso", "rest"), (506, "reposo", "repose"),
    (507, "quietud", "quietness"), (508, "serenidad", "serenity"), (509, "calma", "calm"),
    (510, "tranquilidad", "tranquility"), (511, "paz", "peace"), (512, "reposo", "peace"),
    (513, "conciliabulo", "meeting"), (514, "conciliación", "conciliation"), (515, "avenencia", "agreement"),
    (516, "acuerdo", "agreement"), (517, "pacto", "pact"), (518, "tratado", "treaty"),
    (519, "contrato", "contract"), (520, "convenio", "agreement"), (521, "estipulación", "stipulation"),
    (522, "condición", "condition"), (523, "término", "term"), (524, "cláusula", "clause"),
    (525, "disposición", "disposition"), (526, "artículo", "article"), (527, "inciso", "clause"),
    (528, "párrafo", "paragraph"), (529, "sección", "section"), (530, "capítulo", "chapter"),
    (531, "tomo", "volume"), (532, "libro", "book"), (533, "novela", "novel"),
    (534, "cuento", "story"), (535, "relato", "tale"), (536, "narración", "narrative"),
    (537, "exposición", "exposition"), (538, "descripción", "description"), (539, "retrato", "portrait"),
    (540, "semblanza", "sketch"), (541, "pintura", "painting"), (542, "lienzo", "canvas"),
    (543, "cuadro", "picture"), (544, "escena", "scene"), (545, "vista", "view"),
    (546, "panorama", "panorama"), (547, "perspectiva", "perspective"), (548, "horizonte", "horizon"),
    (549, "fondo", "background"), (550, "primer plano", "foreground"), (551, "plano", "plane"),
    (552, "nivel", "level"), (553, "grado", "degree"), (554, "rango", "rank"),
    (555, "categoría", "category"), (556, "clase", "class"), (557, "tipo", "type"),
    (558, "género", "gender/genre"), (559, "especie", "species"), (560, "variedad", "variety"),
    (561, "clase", "kind"), (562, "forma", "form"), (563, "figura", "figure"),
    (564, "configuración", "configuration"), (565, "estructura", "structure"), (566, "construcción", "construction"),
    (567, "edificio", "building"), (568, "monumento", "monument"), (569, "fortaleza", "fortress"),
    (570, "castillo", "castle"), (571, "palacio", "palace"), (572, "mansión", "mansion"),
    (573, "vivienda", "dwelling"), (574, "residencia", "residence"), (575, "morada", "abode"),
    (576, "hogar", "home"), (577, "habitación", "room"), (578, "aposento", "chamber"),
    (579, "dormitorio", "bedroom"), (580, "alcoba", "bedroom"), (581, "cuarto", "room"),
    (582, "sala", "living room"), (583, "salón", "hall"), (584, "comedor", "dining room"),
    (585, "cocina", "kitchen"), (586, "despensa", "pantry"), (587, "bodega", "wine cellar"),
    (588, "sótano", "basement"), (589, "ático", "attic"), (590, "desván", "attic"),
    (591, "tejado", "roof"), (592, "techo", "ceiling"), (593, "suelo", "floor"),
    (594, "piso", "floor"), (595, "paredes", "walls"), (596, "pared", "wall"),
    (597, "tabique", "partition"), (598, "puerta", "door"), (599, "ventana", "window"),
    (600, "balcón", "balcony"), (601, "terraza", "terrace"), (602, "portal", "entrance"),
    (603, "vestíbulo", "vestibule"), (604, "pasillo", "hall"), (605, "corredor", "corridor"),
    (606, "escalera", "stairs"), (607, "ascensor", "elevator"), (608, "escalerilla", "ladder"),
    (609, "muebles", "furniture"), (610, "silla", "chair"), (611, "sillón", "armchair"),
    (612, "sofá", "sofa"), (613, "banco", "bench"), (614, "cama", "bed"),
    (615, "colchón", "mattress"), (616, "almohada", "pillow"), (617, "sábana", "sheet"),
    (618, "manta", "blanket"), (619, "colcha", "quilt"), (620, "cortina", "curtain"),
    (621, "persiana", "blind"), (622, "estores", "blinds"), (623, "tapete", "mat"),
    (624, "alfombra", "carpet"), (625, "cuadro", "picture"), (626, "fotografía", "photograph"),
    (627, "espejo", "mirror"), "lamparas", "lamps"), (628, "lámpara", "lamp"), (629, "luz", "light"),
    (630, "vela", "candle"), (631, "farol", "lantern"), (632, "antorcha", "torch"),
    (633, "bombilla", "bulb"), (634, "foco", "focus/light"), (635, "reflector", "reflector"),
    (636, "proyector", "projector"), (637, "reloj", "watch/clock"), (638, "péndola", "pendulum"),
    (639, "relojería", "clockwork"), (640, "cronómetro", "chronometer"), (641, "temporizador", "timer"),
    (642, "calendario", "calendar"), (643, "almanaque", "almanac"), (644, "fecha", "date"),
    (645, "era", "era"), (646, "época", "epoch"), (647, "edad", "age"),
    (648, "siglo", "century"), (649, "década", "decade"), (650, "año", "year"),
    (651, "mes", "month"), (652, "semana", "week"), (653, "día", "day"),
    (654, "hora", "hour"), (655, "minuto", "minute"), (656, "segundo", "second"),
    (657, "mañana", "morning"), (658, "tarde", "afternoon"), (659, "noche", "night"),
    (660, "medianoche", "midnight"), (661, "mediodía", "noon"), (662, "amanecer", "dawn"),
    (663, "amanecida", "daybreak"), (664, "alba", "dawn"), (665, "atardecer", "dusk"),
    (666, "ocaso", "sunset"), (667, "crepúsculo", "twilight"), (668, "penumbra", "gloom"),
    (669, "oscuridad", "darkness"), (670, "tinieblas", "darkness"), (671, "sombra", "shadow"),
    (672, "penumbra", "penumbra"), (673, "luz", "light"), (674, "claridad", "clarity"),
    (675, "resplandor", "glow"), (676, "brillo", "shine"), (677, "fulgor", "brightness"),
    (678, "destello", "glint"), (679, "parpadeo", "flicker"), (680, "chispa", "spark"),
    (681, "llama", "flame"), (682, "fuego", "fire"), (683, "incendio", "fire"),
    (684, "hoguera", "bonfire"), (685, "fogata", "campfire"), (686, "chimenea", "fireplace"),
    (687, "horno", "oven"), (688, "estufa", "stove"), (689, "radiador", "radiator"),
    (690, "calefación", "heating"), (691, "aire acondicionado", "air conditioning"), (692, "ventilador", "fan"),
    (693, "climatización", "air conditioning"), (694, "temperatura", "temperature"), (695, "frío", "cold"),
    (696, "calor", "heat"), (697, "ardor", "ardor"), (698, "tibieza", "warmth"),
    (699, "suavidad", "softness"), (700, "dureza", "hardness"), (701, "rigidez", "rigidity"),
    (702, "flexibilidad", "flexibility"), (703, "elasticidad", "elasticity"), (704, "tensión", "tension"),
    (705, "presión", "pressure"), (706, "fuerza", "force/strength"), (707, "potencia", "power"),
    (708, "energía", "energy"), (709, "vigor", "vigor"), (710, "fuerza", "strength"),
    (711, "debilidad", "weakness"), (712, "fragilidad", "fragility"), (713, "delicadeza", "delicacy"),
    (714, "finura", "fineness"), (715, "sutileza", "subtlety"), (716, "refinamiento", "refinement"),
    (717, "elegancia", "elegance"), (718, "gracia", "grace"), (719, "belleza", "beauty"),
    (720, "hermosura", "beauty"), (721, "buen aspecto", "good looks"), (722, "atractivo", "attractiveness"),
    (723, "hechizo", "charm"), (724, "encanto", "charm"), (725, "fascinación", "fascination"),
    (726, "seducción", "seduction"), (727, "tentación", "temptation"), (728, "atracción", "attraction"),
    (729, "afinidad", "affinity"), (730, "simpatía", "sympathy"), (731, "empatía", "empathy"),
    (732, "comprensión", "understanding"), (733, "tolerancia", "tolerance"), (734, "paciencia", "patience"),
    (735, "resignación", "resignation"), (736, "conformidad", "conformity"), (737, "aceptación", "acceptance"),
    (738, "consentimiento", "consent"), (739, "aprobación", "approval"), (740, "visto bueno", "approval"),
    (741, "autorización", "authorization"), (742, "permiso", "permission"), (743, "licencia", "license"),
    (744, "privilegio", "privilege"), (745, "prerrogativa", "prerogative"), (746, "derecho", "right"),
    (747, "libertad", "freedom"), (748, "independencia", "independence"), (749, "autonomía", "autonomy"),
    (750, "soberanía", "sovereignty"), (751, "poder", "power"), (752, "autoridad", "authority"),
    (753, "jurisdicción", "jurisdiction"), (754, "dominio", "domain"), "territorio", "territory"), (755, "territorio", "territory"),
    (756, "región", "region"), (757, "zona", "zone"), (758, "área", "area"),
    (759, "sector", "sector"), (760, "distrito", "district"), (761, "provincia", "province"),
    (762, "estado", "state"), (763, "condado", "county"), (764, "municipio", "municipality"),
    (765, "ciudad", "city"), (766, "vila", "town"), (767, "pueblo", "village"),
    (768, "lugar", "place"), (769, "sitio", "site"), (770, "emplazamiento", "location"),
    (771, "posición", "position"), (772, "ubicación", "location"), (773, "localización", "localization"),
    (774, "paradero", "whereabouts"), (775, "destino", "destination"), (776, "origen", "origin"),
    (777, "procedencia", "source"), (778, "comienzo", "beginning"), (779, "principio", "principle"),
    (780, "inicio", "start"), (781, "inauguración", "inauguration"), (782, "estreno", "debut"),
    (783, "apertura", "opening"), (784, "introducción", "introduction"), (785, "prólogo", "prologue"),
    (786, "preámbulo", "preamble"), (787, "preludio", "prelude"), (788, "antecedente", "antecedent"),
    (789, "trasfondo", "background"), (790, "contexto", "context"), (791, "marco", "framework"),
    (792, "escenario", "scenario"), (793, "telón de fondo", "backdrop"), (794, "decorado", "setting"),
    (795, "utilería", "props"), (796, "atrezzo", "props"), (797, "equipamiento", "equipment"),
    (798, "aparataje", "apparatus"), (799, "maquinaria", "machinery"), (800, "mecanismo", "mechanism"),
    (801, "dispositivo", "device"), (802, "artefacto", "artifact"), (803, "ingenio", "device"),
    (804, "invención", "invention"), (805, "creación", "creation"), (806, "obra", "work"),
    (807, "producto", "product"), "manufactura", "manufactured goods"), (808, "manufactura", "manufacture"),
    (809, "confección", "making"), (810, "elaboración", "elaboration"), (811, "producción", "production"),
    (812, "fabricación", "manufacture"), (813, "construcción", "construction"), (814, "composición", "composition"),
    (815, "organización", "organization"), (816, "estructura", "structure"), (817, "composición", "composition"),
    (818, "constitución", "constitution"), (819, "naturaleza", "nature"), (820, "esencia", "essence"),
    (821, "sustancia", "substance"), (822, "materia", "matter"), (823, "material", "material"),
    (824, "elemento", "element"), (825, "componente", "component"), (826, "ingrediente", "ingredient"),
    (827, "factor", "factor"), (828, "agente", "agent"), (829, "causa", "cause"),
    (830, "motivo", "motif/reason"), (831, "razón", "reason"), (832, "fundamento", "foundation"),
    (833, "base", "base"), (834, "origen", "origin"), (835, "raíz", "root"),
    (836, "etimología", "etymology"), (837, "genealogía", "genealogy"), (838, "ascendencia", "ancestry"),
    (839, "linaje", "lineage"), (840, "parentesco", "kinship"), (841, "relación", "relationship"),
    (842, "vínculo", "bond"), (843, "nexo", "nexus"), (844, "conexión", "connection"),
    (845, "enlace", "link"), (846, "unión", "union"), (847, "fusión", "fusion"),
    (848, "coalición", "coalition"), (849, "alianza", "alliance"), (850, "confederación", "confederation"),
    (851, "federación", "federation"), (852, "liga", "league"), (853, "sindicato", "labor union"),
    (854, "gremio", "guild"), (855, "asociación", "association"), (856, "sociedad", "society"),
    (857, "corporación", "corporation"), (858, "empresa", "company"), (859, "negocio", "business"),
    (860, "comercio", "commerce"), (861, "mercado", "market"), (862, "bolsa", "stock exchange"),
    (863, "banco", "bank"), (864, "finanzas", "finances"), (865, "economía", "economy"),
    (866, "presupuesto", "budget"), (867, "ingreso", "income"), (868, "egreso", "expense"),
    (869, "gasto", "spending"), (870, "costo", "cost"), (871, "precio", "price"),
    (872, "valor", "value"), (873, "cantidad", "quantity"), (874, "número", "number"),
    (875, "cifra", "figure"), (876, "guarismo", "numeral"), (877, "dígito", "digit"),
    (878, "cálculo", "calculation"), (879, "operación", "operation"), (880, "suma", "sum"),
    (881, "resta", "subtraction"), (882, "multiplicación", "multiplication"), (883, "división", "division"),
    (884, "porcentaje", "percentage"), (885, "proporción", "proportion"), (886, "razón", "ratio"),
    (887, "escala", "scale"), (888, "medida", "measure"), (889, "magnitud", "magnitude"),
    (890, "dimensión", "dimension"), (891, "tamaño", "size"), (892, "volumen", "volume"),
    (893, "capacidad", "capacity"), (894, "contenido", "content"), (895, "peso", "weight"),
    (896, "densidad", "density"), (897, "gravi dad", "gravity"), (898, "masa", "mass"),
    (899, "materia", "matter"), (900, "sustancia", "substance"), (901, "compuesto", "compound"),
    (902, "elemento", "element"), (903, "átomo", "atom"), (904, "molécula", "molecule"),
    (905, "célula", "cell"), (906, "protoplasma", "protoplasm"), (907, "núcleo", "nucleus"),
    (908, "órgano", "organ"), (909, "tejido", "tissue"), (910, "aparato", "apparatus"),
    (911, "sistema", "system"), (912, "función", "function"), (913, "actividad", "activity"),
    (914, "movimiento", "movement"), (915, "desplazamiento", "displacement"), (916, "viaje", "trip"),
    (917, "recorrido", "route"), (918, "trayecto", "trajectory"), (919, "camino", "path"),
    (920, "vía", "way"), (921, "carretera", "highway"), (922, "calle", "street"),
    (923, "avenida", "avenue"), (924, "paseo", "promenade"), (925, "sendero", "path"),
    (926, "vereda", "path"), (927, "pista", "track"), (928, "surco", "furrow"),
    (929, "huella", "footprint"), (930, "marca", "mark"), (931, "rastro", "trace"),
    (932, "indicio", "indication"), (933, "síntoma", "symptom"), (934, "signo", "sign"),
    (935, "señal", "signal"), (936, "seña", "sign"), (937, "gesto", "gesture"),
    (938, "expresión", "expression"), (939, "mirada", "look"), (940, "semblante", "face"),
    (941, "fisionomía", "physiognomy"), (942, "aspecto", "aspect"), (943, "apariencia", "appearance"),
    (944, "presencia", "presence"), (945, "existencia", "existence"), (946, "realidad", "reality"),
    (947, "verdad", "truth"), (948, "Dios", "God"), (949, "Ser Supremo", "Supreme Being"),
    (950, "Providencia", "Providence"), (951, "destino", "fate"), (952, "suerte", "fortune"),
    (953, "azar", "chance"), (954, "acaso", "perhaps"), (955, "casualidad", "coincidence"),
    (956, "probabilidad", "probability"), (957, "posibilidad", "possibility"), (958, "eventualidad", "eventuality"),
    (959, "hipótesis", "hypothesis"), (960, "supuesto", "assumption"), (961, "conjetura", "conjecture"),
    (962, "especulación", "speculation"), (963, "teoría", "theory"), (964, "práctica", "practice"),
    (965, "experiencia", "experience"), (966, "vivencia", "experience"), (967, "aventura", "adventure"),
    (968, "hazaña", "feat"), (969, "proeza", "exploit"), (970, "gesta", "deed"),
    (971, "acción", "action"), (972, "hecho", "fact"), (973, "acontecimiento", "event"),
    (974, "suceso", "event"), (975, "incidente", "incident"), (976, "episodio", "episode"),
    (977, "capítulo", "chapter"), (978, "escena", "scene"), (979, "acto", "act"),
    (980, "cuadro", "tableau"), (981, "cuadro", "painting"), (982, "retrato", "portrait"),
    (983, "busto", "bust"), (984, "escultura", "sculpture"), (985, "estatua", "statue"),
    (986, "monumento", "monument"), (987, "obelisco", "obelisk"), (988, "pirámide", "pyramid"),
    (989, "arco", "arch"), (990, "bóveda", "vault"), (991, "columna", "column"),
    (992, "pilastra", "pilaster"), (993, "basamento", "base"), (994, "pedestal", "pedestal"),
    (995, "plataforma", "platform"), (996, "estrado", "dais"), (997, "trono", "throne"),
    (998, "asiento", "seat"), (999, "lugar", "place"), (1000, "espacio", "space"),
]

# Save to file
js_output = "const spanish_english = [\n"
for rank, word, translation in spanish_1000_complete:
    js_output += f'  {{ "rank": {rank}, "foreign": "{word}", "english": "{translation}" }},\n'
# Remove trailing comma from last entry
js_output = js_output.rstrip(',\n') + '\n'
js_output += "];\n"

with open('languages/spanish_english.js', 'w', encoding='utf-8') as f:
    f.write(js_output)

print(f"Successfully created spanish_english.js with {len(spanish_1000_complete)} words")
